### PR TITLE
Create de.json

### PR DESCRIPTION
**Pull request by cbuschbeck**

### CODE REVIEW

**Comment by aturri** [comment]
For me is ok!
Thanks 😊

**Comment by cbuschbeck** [comment]
Hi Aturri,

Any idea why my Inverter do not connect?

Debug:
2023-08-19 14:15:08.220 WARNING (MainThread) [custom_components.zcsazzurro.api] Unable to parse result from ZCS Azzurro portal: INVALID CLIENT
2023-08-19 14:15:08.224 DEBUG (MainThread) [custom_components.zcsazzurro] Data for ZP1*****260: {}
2023-08-19 14:15:08.224 DEBUG (MainThread) [custom_components.zcsazzurro] Finished fetching zcsazzurro data in 0.103 seconds (success: True)
2023-08-19 14:15:08.226 DEBUG (MainThread) [custom_components.zcsazzurro.sensor] init sensor status-ZP1*****260
2023-08-19 14:15:08.226 DEBUG (MainThread) [custom_components.zcsazzurro.sensor] init sensor power_generating-ZP1*****260


configuration.yaml
Auth_key and Client_Code was used with quotes, simple one ' and doubles    "

Still no connection since three days.

Best,
Christoph

**Comment by aturri** [comment]
Yeah, log is saying that you are providing invalid credentials.
Make sure that you are including the "Zcs " prefix in auth key.

zcsazzurro:
  auth_key: 'Zcs xxx'
  client_code: 'client code'

**Comment by cbuschbeck** [comment]
Yes, the support gave me the auth_key, but no client_code, they say it is the serial number of the device.
From your documentation it seems that serial number is related to thing_key. Right? So what’s the client_code then?

**Comment by aturri** [comment]
I received an email with a PDF attached. Inside the PDF it was mentioned only the auth key. I found the client code in the text of the email.

**Comment by aturri** [comment]
Yeah, the thing key is the serial number that you can add from frontend when setting up the integration.

**Pull request closed without merging**
